export default {
    sobr: [
        {
            name: "agencia",
			active: false,
			group: 'group1',
            options: []
        },
        {
            name: "independiente",
			active: false,
			group: 'group1',
            options: []
        },
        {
			name: "delgada",
			group: 'group2',
            active: false,
            options: []
        },
        {
			name: "rellenita",
			group: 'group2',
            active: false,
            options: []
        }, {
			name: "sin depilar",
			group: 'group3',
            active: false,
            options: []
        }, {
			name: "depilada",
			group: 'group3',
            active: false,
            options: []
        }, {
			name: "alta",
			group: 'group4',
            active: false,
            options: []
        }, {
			name: "menudita",
			group: 'group4',
            active: false,
            options: []
        }, {
			name: "pelirroja",
			group: 'group5',
            active: false,
            options: []
        }, {
			name: "morena",
			group: 'group5',
            active: false,
            options: []
        }, {
			name: "rubia",
			group: 'group5',
            active: false,
            options: []
        }, {
            name: "pecho natural",
			active: false,
			group: 'group6',
            options: []
        }, {
			name: "tarjeta de crédito",
			group: 'group7',
            active: false,
            options: []
        }, {
			name: "atención a mujeres",
			group: 'group8',
            active: false,
            options: []
        }, {
			name: "tetas grandes",
			group: 'group9',
            active: false,
            options: []
        }, {
			name: "atención a parejas",
			group: 'group10',
            active: false,
            options: []
        }, {
			name: "whatsapp",
			group: 'group11',
            active: false,
            options: []
        }, {
			name: "Etnia",
			group: 'group12',
            active: false,
            options: [
                {
                    name: "latina",
                    active: false
                }, {
                    name: "mulata",
                    active: false
                }, {
                    name: "negra",
                    active: false
                }, {
                    name: "asiatica",
                    active: false
                }
            ]
        }, {
            name: "País",
			active: false,
			group: 'group13',
            options: [
                {
                    name: "española",
                    active: false
                },
                {
                    name: "andaluza",
                    active: false
                },
                {
                    name: "aragonesa",
                    active: false
                },
                {
                    name: "asturiana",
                    active: false
                }, {
                    name: "baleara",
                    active: false
                }, {
                    name: "canaria",
                    active: false
                }, {
                    name: "cantabra",
                    active: false
                }, {
                    name: "castellana",
                    active: false
                }, {
                    name: "catalana",
                    active: false
                }, {
                    name: "extremeña",
                    active: false
                }, {
                    name: "gallega",
                    active: false
                }, {
                    name: "leonesa",
                    active: false
                }, {
                    name: "madrileña",
                    active: false
                }, {
                    name: "manchega",
                    active: false
                }, {
                    name: "murciana",
                    active: false
                }, {
                    name: "navarra",
                    active: false
                }, {
                    name: "riojana",
                    active: false
                }, {
                    name: "valenciana",
                    active: false
                }, {
                    name: "vasca",
                    active: false
                }, {
                    name: "alemana",
                    active: false
                }, {
                    name: "andorrana",
                    active: false
                }, {
                    name: "arabe",
                    active: false
                }, {
                    name: "argelina",
                    active: false
                }, {
                    name: "argentina",
                    active: false
                }, {
                    name: "australiana",
                    active: false
                }, {
                    name: "austriaca",
                    active: false
                }, {
                    name: "belga",
                    active: false
                }, {
                    name: "bielorrusa",
                    active: false
                }, {
                    name: "boliviana",
                    active: false
                }, {
                    name: "bosnia",
                    active: false
                }, {
                    name: "brasileña",
                    active: false
                }, {
                    name: "bulgara",
                    active: false
                }, {
                    name: "camerunesa",
                    active: false
                }, {
                    name: "canadiense",
                    active: false
                }, {
                    name: "checa",
                    active: false
                }, {
                    name: "chilena",
                    active: false
                }, {
                    name: "china",
                    active: false
                }, {
                    name: "colombiana",
                    active: false
                }, {
                    name: "coreana",
                    active: false
                }, {
                    name: "costarricense",
                    active: false
                }, {
                    name: "croata",
                    active: false
                }, {
                    name: "cubana",
                    active: false
                }, {
                    name: "danesa",
                    active: false
                }, {
                    name: "dominicana",
                    active: false
                }, {
                    name: "ecuatoriana",
                    active: false
                }, {
                    name: "egipcia",
                    active: false
                }, {
                    name: "escocesa",
                    active: false
                }, {
                    name: "eslovaca",
                    active: false
                }, {
                    name: "eslovena",
                    active: false
                }, {
                    name: "estadounidense",
                    active: false
                }, {
                    name: "estonia",
                    active: false
                }, {
                    name: "etiope",
                    active: false
                }, {
                    name: "filipina",
                    active: false
                }, {
                    name: "finlandesa",
                    active: false
                }, {
                    name: "francesa",
                    active: false
                }, {
                    name: "galesa",
                    active: false
                }, {
                    name: "griega",
                    active: false
                }, {
                    name: "guatemalteca",
                    active: false
                }, {
                    name: "guineana",
                    active: false
                }, {
                    name: "holandesa",
                    active: false
                }, {
                    name: "hondureña",
                    active: false
                }, {
                    name: "hungara",
                    active: false
                }, {
                    name: "india",
                    active: false
                }, {
                    name: "indonesia",
                    active: false
                }, {
                    name: "inglesa",
                    active: false
                }, {
                    name: "irlandesa",
                    active: false
                }, {
                    name: "israelí",
                    active: false
                }, {
                    name: "italiana",
                    active: false
                }, {
                    name: "jamaicana",
                    active: false
                }, {
                    name: "japonesa",
                    active: false
                }, {
                    name: "jordana",
                    active: false
                }, {
                    name: "keniata",
                    active: false
                }, {
                    name: "letona",
                    active: false
                }, {
                    name: "libanesa",
                    active: false
                }, {
                    name: "lituana",
                    active: false
                }, {
                    name: "luxemburguesa",
                    active: false
                }, {
                    name: "macedonia",
                    active: false
                }, {
                    name: "marfileña",
                    active: false
                }, {
                    name: "marroqui",
                    active: false
                }, {
                    name: "mexicana",
                    active: false
                }, {
                    name: "moldava",
                    active: false
                }, {
                    name: "montenegrina",
                    active: false
                }, {
                    name: "neozelandesa",
                    active: false
                }, {
                    name: "nicaraguense",
                    active: false
                }, {
                    name: "nigeriana",
                    active: false
                }, {
                    name: "noruega",
                    active: false
                }, {
                    name: "panameña",
                    active: false
                }, {
                    name: "paraguaya",
                    active: false
                }, {
                    name: "peruana",
                    active: false
                }, {
                    name: "polaca",
                    active: false
                }, {
                    name: "portuguesa",
                    active: false
                }, {
                    name: "puertorriqueña",
                    active: false
                }, {
                    name: "rumana",
                    active: false
                }, {
                    name: "rusa",
                    active: false
                }, {
                    name: "salvadoreña",
                    active: false
                }, {
                    name: "senegalesa",
                    active: false
                }, {
                    name: "serbia",
                    active: false
                }, {
                    name: "sudafricana",
                    active: false
                }, {
                    name: "sueca",
                    active: false
                }, {
                    name: "suiza",
                    active: false
                }, {
                    name: "tailandesa",
                    active: false
                }, {
                    name: "tunecina",
                    active: false
                }, {
                    name: "turca",
                    active: false
                }, {
                    name: "ucraniana",
                    active: false
                }, {
                    name: "uruguaya",
                    active: false
                }, {
                    name: "venezolana",
                    active: false
                }, {
                    name: "africana",
                    active: false
                }, {
                    name: "americana",
                    active: false
                }, {
                    name: "anglosajona",
                    active: false
                }, {
                    name: "baltica",
                    active: false
                }, {
                    name: "britanica",
                    active: false
                }, {
                    name: "caribeña",
                    active: false
                }, {
                    name: "centroamericana",
                    active: false
                }, {
                    name: "eslava",
                    active: false
                }, {
                    name: "europa del este",
                    active: false
                }, {
                    name: "magrebie",
                    active: false
                }, {
                    name: "nordica",
                    active: false
                }, {
                    name: "oriente medio",
                    active: false
                }, {
                    name: "sudamericana",
                    active: false
                }, {
                    name: "yugoslava",
                    active: false
                }
            ]
        },
    ]
}
